const locations = [
  // Egypt
  {
    latitude: 30.0444,
    longitude: 31.2357,
    country: "Egypt",
    countryAr: "مصر",
    city: "Cairo",
    cityAr: "القاهرة",
  },
  {
    latitude: 31.2001,
    longitude: 29.9187,
    country: "Egypt",
    countryAr: "مصر",
    city: "Alexandria",
    cityAr: "الإسكندرية",
  },
  {
    latitude: 30.0131,
    longitude: 31.2089,
    country: "Egypt",
    countryAr: "مصر",
    city: "Giza",
    cityAr: "الجيزة",
  },
  {
    latitude: 31.2653,
    longitude: 32.3019,
    country: "Egypt",
    countryAr: "مصر",
    city: "Port Said",
    cityAr: "بورسعيد",
  },
  {
    latitude: 29.9668,
    longitude: 32.5498,
    country: "Egypt",
    countryAr: "مصر",
    city: "Suez",
    cityAr: "السويس",
  },
  {
    latitude: 31.0409,
    longitude: 31.3785,
    country: "Egypt",
    countryAr: "مصر",
    city: "Mansoura",
    cityAr: "المنصورة",
  },
  {
    latitude: 30.7865,
    longitude: 31.0004,
    country: "Egypt",
    countryAr: "مصر",
    city: "Tanta",
    cityAr: "طنطا",
  },
  {
    latitude: 30.5877,
    longitude: 31.502,
    country: "Egypt",
    countryAr: "مصر",
    city: "Zagazig",
    cityAr: "الزقازيق",
  },
  {
    latitude: 31.4175,
    longitude: 31.8144,
    country: "Egypt",
    countryAr: "مصر",
    city: "Damietta",
    cityAr: "دمياط",
  },
  {
    latitude: 29.3084,
    longitude: 30.8428,
    country: "Egypt",
    countryAr: "مصر",
    city: "Fayoum",
    cityAr: "الفيوم",
  },
  {
    latitude: 29.0661,
    longitude: 31.0994,
    country: "Egypt",
    countryAr: "مصر",
    city: "Beni Suef",
    cityAr: "بني سويف",
  },
  {
    latitude: 28.1099,
    longitude: 30.7503,
    country: "Egypt",
    countryAr: "مصر",
    city: "Minya",
    cityAr: "المنيا",
  },
  {
    latitude: 27.1809,
    longitude: 31.1837,
    country: "Egypt",
    countryAr: "مصر",
    city: "Asyut",
    cityAr: "أسيوط",
  },
  {
    latitude: 26.5591,
    longitude: 31.6957,
    country: "Egypt",
    countryAr: "مصر",
    city: "Sohag",
    cityAr: "سوهاج",
  },
  {
    latitude: 26.1551,
    longitude: 32.716,
    country: "Egypt",
    countryAr: "مصر",
    city: "Qena",
    cityAr: "قنا",
  },
  {
    latitude: 25.6872,
    longitude: 32.6396,
    country: "Egypt",
    countryAr: "مصر",
    city: "Luxor",
    cityAr: "الأقصر",
  },
  {
    latitude: 24.0889,
    longitude: 32.8998,
    country: "Egypt",
    countryAr: "مصر",
    city: "Aswan",
    cityAr: "أسوان",
  },
  {
    latitude: 27.2579,
    longitude: 33.8116,
    country: "Egypt",
    countryAr: "مصر",
    city: "Hurghada",
    cityAr: "الغردقة",
  },
  {
    latitude: 27.9158,
    longitude: 34.3299,
    country: "Egypt",
    countryAr: "مصر",
    city: "Sharm El Sheikh",
    cityAr: "شرم الشيخ",
  },
  {
    latitude: 31.3543,
    longitude: 27.2373,
    country: "Egypt",
    countryAr: "مصر",
    city: "Marsa Matruh",
    cityAr: "مرسى مطروح",
  },
  {
    latitude: 31.1316,
    longitude: 33.7984,
    country: "Egypt",
    countryAr: "مصر",
    city: "Arish",
    cityAr: "العريش",
  },

  // Lebanon
  {
    latitude: 33.8938,
    longitude: 35.5018,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Beirut",
    cityAr: "بيروت",
  },
  {
    latitude: 34.4332,
    longitude: 35.8441,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Tripoli",
    cityAr: "طرابلس",
  },
  {
    latitude: 33.5571,
    longitude: 35.3729,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Sidon",
    cityAr: "صيدا",
  },
  {
    latitude: 33.2705,
    longitude: 35.2038,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Tyre",
    cityAr: "صور",
  },
  {
    latitude: 33.8463,
    longitude: 35.902,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Zahle",
    cityAr: "زحلة",
  },
  {
    latitude: 33.9808,
    longitude: 35.6178,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Jounieh",
    cityAr: "جونية",
  },
  {
    latitude: 34.1211,
    longitude: 35.6481,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Byblos",
    cityAr: "جبيل",
  },
  {
    latitude: 34.0047,
    longitude: 36.211,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Baalbek",
    cityAr: "بعلبك",
  },
  {
    latitude: 33.3772,
    longitude: 35.4833,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Nabatieh",
    cityAr: "النبطية",
  },
  {
    latitude: 34.2553,
    longitude: 35.6581,
    country: "Lebanon",
    countryAr: "لبنان",
    city: "Batroun",
    cityAr: "البترون",
  },

  // Saudi Arabia
  {
    latitude: 24.7136,
    longitude: 46.6753,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Riyadh",
    cityAr: "الرياض",
  },
  {
    latitude: 21.4858,
    longitude: 39.1925,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Jeddah",
    cityAr: "جدة",
  },
  {
    latitude: 21.3891,
    longitude: 39.8579,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Mecca",
    cityAr: "مكة المكرمة",
  },
  {
    latitude: 24.5247,
    longitude: 39.5692,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Medina",
    cityAr: "المدينة المنورة",
  },
  {
    latitude: 26.4207,
    longitude: 50.0888,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Dammam",
    cityAr: "الدمام",
  },
  {
    latitude: 26.2172,
    longitude: 50.1971,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Khobar",
    cityAr: "الخبر",
  },
  {
    latitude: 21.2703,
    longitude: 40.4158,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Taif",
    cityAr: "الطائف",
  },
  {
    latitude: 28.3838,
    longitude: 36.555,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Tabuk",
    cityAr: "تبوك",
  },
  {
    latitude: 18.2164,
    longitude: 42.5053,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Abha",
    cityAr: "أبها",
  },
  {
    latitude: 16.8892,
    longitude: 42.5511,
    country: "Saudi Arabia",
    countryAr: "السعودية",
    city: "Jazan",
    cityAr: "جازان",
  },

  // United Arab Emirates
  {
    latitude: 24.4539,
    longitude: 54.3773,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Abu Dhabi",
    cityAr: "أبو ظبي",
  },
  {
    latitude: 25.2048,
    longitude: 55.2708,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Dubai",
    cityAr: "دبي",
  },
  {
    latitude: 25.3463,
    longitude: 55.4209,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Sharjah",
    cityAr: "الشارقة",
  },
  {
    latitude: 25.4052,
    longitude: 55.5136,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Ajman",
    cityAr: "عجمان",
  },
  {
    latitude: 24.2075,
    longitude: 55.7447,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Al Ain",
    cityAr: "العين",
  },
  {
    latitude: 25.8007,
    longitude: 55.9762,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Ras Al Khaimah",
    cityAr: "رأس الخيمة",
  },
  {
    latitude: 25.1288,
    longitude: 56.3265,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Fujairah",
    cityAr: "الفجيرة",
  },
  {
    latitude: 25.5647,
    longitude: 55.5552,
    country: "United Arab Emirates",
    countryAr: "الإمارات العربية المتحدة",
    city: "Umm Al Quwain",
    cityAr: "أم القيوين",
  },
];

export default locations;
